# Generated by Django 3.1.7 on 2021-03-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
