# Generated by Django 3.1.7 on 2021-03-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0002_userinfo_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCode',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=30)),
            ],
        ),
    ]
