# Generated by Django 3.1.7 on 2021-04-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0008_auto_20210403_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='item_name',
            field=models.CharField(blank=True, help_text='상품명을 입력하세요', max_length=50),
        ),
    ]
