# Generated by Django 3.1.7 on 2021-04-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0009_advertisement_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='item_name',
            field=models.CharField(help_text='상품명을 입력하세요', max_length=50),
        ),
    ]
