# Generated by Django 3.1.7 on 2021-05-10 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0013_auto_20210419_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='lunch_type_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='menureview',
            name='enroll_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 10, 20, 38, 52, 569328)),
        ),
    ]
